#!/usr/bin/env python
# -*- coding: utf-8 -*-
##
# @file     rtimer-ext-calibration.py
# @author   Kyeong Soo (Joseph) Kim <kyeongsoo.kim@gmail.com>
# @date     2026-02-28
#
# @brief    Automate the calibration of the extended rtimer using timing signal
#           generated by a remote Raspberry Pi.
#
# @remarks  Copyright (C) 2026 Kyeong Soo (Joseph) Kim. All rights reserved.
#
# @remarks  This software is written and distributed under the GNU General
#           Public License Version 2 (http://www.gnu.org/licenses/gpl-2.0.html).
#           You must not remove this notice, or any other, from this software.
#

import docker
import os
import re
import subprocess
import sys
from gpiozero import LED
from time import sleep


# customize the environment for the remote Raspberry Pi
custom_env = os.environ.copy()
custom_env["PIGPIO_ADDR"] = "192.168.5.100"


client = docker.from_env()
container_id = "e997036a7a71" # contiki-ng docker instance ID
container = client.containers.get(container_id)
working_dir = "/home/user/contiki-ng/examples/iot-time-sync/clock-timer-ext"
tools_dir = "/home/user/contiki-ng/examples/iot-time-sync/tools"


print("make clean ... ")
exit_code, output = container.exec_run(
    cmd="bash -c 'cd " + working_dir + " && make clean'",
    stderr=True,
    stdout=True
)
print(f"Output: {output.decode('utf-8')}")
if exit_code != 0:
    sys.exit(1)

print("make MOTES=/dev/ttyUSB0 rtimer-ext-calibratioin.upload ... ")
exit_code, output = container.exec_run(
    cmd="bash -c 'cd " + working_dir + " && make MOTES=/dev/ttyUSB0 rtimer-ext-calibration.upload'",
    stderr=True,
    stdout=True
)
print(f"Output: {output.decode('utf-8')}")
if exit_code != 0:
    sys.exit(1)

print("make MOTES=/dev/ttyUSB0 login ... ")
exit_code, output_stream = container.exec_run(
    cmd="bash -c 'cd " + working_dir + " && make MOTES=/dev/ttyUSB0 login'",
    stream=True,
    demux=False
)
for line in output_stream:
    line = line.decode('utf-8').strip()
    print(line)
    sys.stdout.flush()

    match = re.search(r"Now ready for triggers", line)
    if match:
        # start timing signal generation on the remote Raspberry Pi
        exit_code, output = container.exec_run(
            cmd="bash -c 'cd " + tools_dir + " && python time_calibration.py'",
            stderr=True,
            stdout=True
        )       
        if exit_code != 0:
            print(f"Output: {output.decode('utf-8')}")
            sys.exit(1)

# print("time_calibration.py subprocess output (stdout):")
# print(result.stdout)
# print("time_calibration.py subprocess error (stderr):")
# print(result.stderr)