#!/usr/bin/env python
# -*- coding: utf-8 -*-
##
# @file     rtimer-ext-calibration.py
# @author   Kyeong Soo (Joseph) Kim <kyeongsoo.kim@gmail.com>
# @date     2026-02-28
#
# @brief    Automate the calibration of the extended rtimer using timing signal
#           generated by a remote Raspberry Pi.
#
# @remarks  Make sure that pigpiod daemon is running on a remote Raspberry Pi.
#
# @remarks  Copyright (C) 2026 Kyeong Soo (Joseph) Kim. All rights reserved.
#
# @remarks  This software is written and distributed under the GNU General
#           Public License Version 2 (http://www.gnu.org/licenses/gpl-2.0.html).
#           You must not remove this notice, or any other, from this software.
#

import docker
import os
import re
import subprocess
import sys
from gpiozero import LED
from time import sleep


# customize the environment for the remote Raspberry Pi
custom_env = os.environ.copy()
custom_env["PIGPIO_ADDR"] = "192.168.5.100"


client = docker.from_env()
containers = client.containers.list(filters={'ancestor': 'contiker/contiki-ng'})
if not containers:
    print("ERROR: No container found for contiker/contiki-ng")
    sys.exit(1)
container_id = containers[0].id
container = client.containers.get(container_id)
working_dir = "/home/user/contiki-ng/examples/iot-time-sync/clock-timer-ext"


command = "make clean" 
print(command)
exit_code, output_stream = container.exec_run(
    cmd=command,
    user="user",
    workdir=working_dir,
    tty=True,
    stream=True,
    demux=False
)
for line in output_stream:
    line = line.decode('utf-8').strip()
    print(line)
    sys.stdout.flush()

command = "make MOTES=/dev/ttyUSB0 rtimer-ext-calibration.upload"
print(command)
exit_code, output_stream = container.exec_run(
    cmd=command,
    user="user",
    workdir=working_dir,
    tty=True,
    stream=True,
    demux=False
)
for line in output_stream:
    line = line.decode('utf-8').strip()
    print(line)
    sys.stdout.flush()

command = "serialdump /dev/ttyUSB0 | tee ./log/rtimer-ext-calibration_$(date +'%Y%m%d%H%M%S').log"
print(command)
process = subprocess.Popen(
    command,
    shell=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)
for line in process.stdout:
    print(line.rstrip()) # Process or print the line in real-time
    sys.stdout.flush()

    match = re.search(r"Now ready for triggers", line)
    if match:
        print("[LOG: main] Start timing signal generation on the remote Raspberry Pi ...")
        # run as a background process to avoid blocking the main process
        process = subprocess.Popen(
            ["python", "../tools/time_calibration.py"],
            env=custom_env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

    match = re.search(r"##### END", line)
    if match:
        # for process_to_kill in ['serialdump', 'tee']:
        for process_to_kill in ['serialdump']:
            try:
                results = subprocess.run(
                    ['pkill', '-x', process_to_kill],
                    stdout=subprocess.PIPE, # merge stdout and stderr
                    stderr=subprocess.STDOUT, 
                    text=True,
                    check=True
                )
                # workaround for the failure in capturing pkill output
                print(f"[LOG: {process_to_kill}] ", end="")
            except subprocess.CalledProcessError:
                print(f"[LOG: {process_to_kill}] {results.stdout}.")

# check and print the output of the background process
stdout, stderr = process.communicate()
for line in stdout.splitlines():
    print(f"[LOG: time_calibration.py] {line}")
process.terminate()