CONTIKI_PROJECT = csc-analysis
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += csc.c
TARGET_LIBFILES += -lm

# disable networking
MAKE_MAC = MAKE_MAC_NULLMAC
MAKE_NET = MAKE_NET_NULLNET

# disable TCP, UDP, and 6lowpan fragmentation
DEFINES += UIP_CONF_TCP=0
DEFINES += UIP_CONF_UDP=0
DEFINES += SICSLOWPAN_CONF_FRAG=0

# disable module logs
DEFINES += LOG_CONF_LEVEL_MAIN=0
DEFINES += LOG_CONF_LEVEL_SKY=0

# optimize CSC implementation
DEFINES += NDEBUG # turn off assert()
DEFINES += CSC_INT_SIZE=4 # number of bytes for 'i', 'D', and 'A' (4 or 8)
DEFINES += CSC_DS_OPT1=1 # turn off iteration couting in DS
DEFINES += CSC_DS_OPT2=1 # enable branchless programming in DS
DEFINES += CSC_DIV_OPT=1 # turn off checking the value of 'A' in division algos

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
