CONTIKI_PROJECT = csc-debug1
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += csc.c
TARGET_LIBFILES += -lm

MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

# disable TCP, UDP, and 6lowpan fragmentation
DEFINES += UIP_CONF_TCP=0
DEFINES += UIP_CONF_UDP=0
DEFINES += SICSLOWPAN_CONF_FRAG=0

# optimize CSC implementation
DEFINES += NDEBUG
DEFINES += CSC_INT_SIZE=8 # number of bytes for 'i', 'D', and 'A' (4 or 8)
# DEFINES += CSC_NO_ITER_CHECK=1 # turn off iteration couting in iterative algorithms
DEFINES += CSC_NO_DIV_CHECK=1 # turn off checking the value of A in division algorithms

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
