CONTIKI_PROJECT = csc-analysis csc-client csc-server
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += csc.c
TARGET_LIBFILES += -lm

MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

# disable TCP, UDP, and 6lowpan fragmentation
DEFINES += UIP_CONF_TCP=0
DEFINES += UIP_CONF_UDP=0
DEFINES += SICSLOWPAN_CONF_FRAG=0

# disable module logs
DEFINES += LOG_CONF_LEVEL_MAIN=0
DEFINES += LOG_CONF_LEVEL_SKY=0

# enable my extensions
DEFINES += NULLNET_EXT=1
# DEFINES += P2_EXT=1 # edge detection and timestamping at P2.1 (GIO1) # now working!
# DEFINES += P2_EXT=3 # edge detection and timestamping at P2.3 (GIO2) # working!
DEFINES += P2_EXT=6 # edge detection and timestamping at P2.6 (GIO3) # working!
DEFINES += RTIMER_EXT=1

# optimize CSC implementation
DEFINES += NDEBUG # turn off assert()
DEFINES += CSC_INT_SIZE=4 # number of bytes for 'i', 'D', and 'A' (4 or 8)
DEFINES += CSC_DS_OPT1=1 # turn off iteration couting in DS
DEFINES += CSC_DS_OPT2 # enable branchless programming in DS
DEFINES += CSC_DIV_OPT # turn off checking the value of A in division algos

# experimental setup
### DEBUG
# DEFINES += BEACON_INTERVAL=1 # beacon interval in seconds
# DEFINES += NB_SKIP=10 # number of initial beacons to skip before CFR initialization
# DEFINES += NB_CFR=100 # number of beacons for CFR initialization
# DEFINES += EVENT_NUMBER_MAX=100 # maximum number of events to process after CFR initialization
### DEBUG
DEFINES += BEACON_INTERVAL=10 # beacon interval in seconds
DEFINES += NB_SKIP=10 # number of initial beacons to skip before CFR initialization
DEFINES += NB_CFR=100 # number of beacons for CFR initialization
DEFINES += EVENT_NUMBER_MAX=100 # maximum number of events to process after CFR initialization

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
